version: '3.8'

services:
  webapp:
    image: "asia.gcr.io/dakshay-goapptiv/my-app:latest"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - myapp_network
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    depends_on:
      - webapp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - myapp_network

networks:
  myapp_network:
    driver: overlay